version: '3'
services:
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - net1
    restart: on-failure

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
     - REACT_APP_API_HOST=todoback

    networks:
      - net1
    restart: on-failure

  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront

    networks:
      - net1
    restart: on-failure

networks:
  net1: