version: '3'
services:
  todobackend:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - net1
    restart: on-failure

  todofrontend:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - todobackend
    environment:
     - REACT_APP_API_HOST=todobackend

    networks:
      - net1
    restart: on-failure

  todotests:
    image: todotests
    depends_on:
      - todofrontend
      - todobackend
    environment:
      - FRONT_HOST=todofrontend

    networks:
      - net1
    restart: on-failure

networks:
  net1: