version: '3'
services:
  back-end:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - net1
    restart: on-failure

  front-end:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
     - REACT_APP_API_HOST=back-end

    networks:
      - net1
    restart: on-failure

  test:
    image: todotests
    depends_on:
      - front-end
      - back-end
    environment:
      - FRONT_HOST=front-end

    networks:
      - net1
    restart: on-failure

networks:
  net1: