version: '3'
services:
  backend:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - net1
    restart: on-failure

  frontend:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
     - REACT_APP_API_HOST=backend
     - REACT_APP_API_PORT=3001
    networks:
      - net1
    restart: on-failure

  test:
    image: todotests
    depends_on:
      - frontend
      - backend
    environment:
      - FRONT_HOST=frontend
      - FRONT_PORT=3000
    networks:
      - net1
    restart: on-failure

networks:
  net1: